# Generated by Django 5.0.3 on 2024-04-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sale_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
