# Generated by Django 5.0.3 on 2024-04-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sale_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product_name',
            new_name='product_sold',
        ),
    ]
