# Generated by Django 5.0.3 on 2024-04-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_product_name_sale_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_sold',
        ),
    ]
